puts "------------creating users----------------"
user = User.create!({ first_name: "Daniel", last_name: "Pericich", username: FFaker::Internet.user_name, role: "admin", email: FFaker::Internet.email, password: FFaker::Internet.password })
user_extra = User.create!({ first_name: "Pixie", last_name: "Doge", username: FFaker::Internet.user_name, role: "trader", email: FFaker::Internet.email, password: FFaker::Internet.password })
puts "created #{User.count} Users"

puts "------------creating articles-------------"
articles = Article.create!([
  { title: "The Great Eggscape", user_id: user.id, created_at: DateTime.now - 1.day,  article_text: "I'm baby master cleanse wayfarers 90's gluten-free vape. Hella normcore raclette green juice, poutine shaman pop-up sriracha hammock semiotics. Narwhal synth try-hard man braid seitan. Listicle cred heirloom butcher, bespoke sustainable craft beer everyday carry. Yuccie chillwave tofu skateboard cred hell of +1 irony jean shorts snackwave af church-key tumeric YOLO trust fund. +1 thundercats lumbersexual meditation 90's bespoke irony, PBR&B fanny pack pop-up tilde.
  Hammock drinking vinegar kale chips franzen. Post-ironic you probably haven't heard of them chambray marfa, hella venmo selvage la croix irony selfies lyft. Tumeric mixtape gentrify tilde fingerstache, cray slow-carb air plant synth prism umami VHS plaid twee. Try-hard fam tbh wayfarers live-edge hashtag DIY pitchfork ennui.
  Venmo 90's live-edge, brunch cray post-ironic iceland deep v lumbersexual helvetica. IPhone prism gastropub keytar tote bag, artisan truffaut cray literally sriracha tousled VHS hella. Listicle tilde wolf, godard squid kale chips skateboard. Tacos pinterest authentic pabst.
  Copper mug wayfarers tilde, XOXO letterpress mlkshk cliche kogi etsy fam health goth. Jianbing mumblecore pok pok kickstarter echo park tilde freegan. Mumblecore chicharrones portland hexagon chartreuse gastropub. Jianbing post-ironic activated charcoal humblebrag food truck. Live-edge master cleanse leggings blog umami meditation roof party.
  Pitchfork jean shorts blog, locavore kinfolk austin bitters. Green juice selfies godard brooklyn trust fund, meh poutine gluten-free leggings photo booth try-hard tbh pug scenester skateboard. Yr vinyl ramps subway tile, bicycle rights cold-pressed pop-up poutine man braid messenger bag austin pinterest offal sustainable. Sartorial cardigan lo-fi fixie before they sold out tilde. Live-edge tofu knausgaard viral microdosing. Four dollar toast keytar swag, taiyaki authentic asymmetrical hoodie biodiesel before they sold out selfies lomo roof party succulents. Vexillologist venmo you probably haven't heard of them gochujang, succulents glossier flexitarian jean shorts whatever kale chips."
  },
  { title: "A Long Road Home", user_id: user.id, created_at: DateTime.now, article_text: "I'm baby normcore tofu sustainable mumblecore YOLO, cliche church-key chia poutine ethical humblebrag cold-pressed. Seitan messenger bag kogi hashtag 90's, tilde bitters biodiesel neutra selfies. Chia poke artisan copper mug, tumeric skateboard cred. Fashion axe blue bottle salvia, disrupt asymmetrical copper mug affogato distillery flannel.
  Chambray brunch readymade art party flannel man braid. Deep v viral taxidermy woke irony try-hard distillery beard before they sold out austin seitan. Plaid tattooed hexagon pickled messenger bag. Raw denim quinoa man bun, air plant PBR&B poke fashion axe neutra actually biodiesel gentrify fanny pack freegan banh mi. Synth pickled schlitz sartorial fingerstache. Umami mlkshk sartorial, adaptogen mixtape cold-pressed deep v lumbersexual gastropub schlitz flannel. Activated charcoal DIY 8-bit pop-up keytar hexagon ugh tilde.
  Portland poke snackwave gochujang vice sustainable. Fashion axe deep v knausgaard echo park. Chillwave roof party hashtag blue bottle selvage shabby chic crucifix whatever vinyl live-edge. Tofu meggings live-edge readymade, church-key jean shorts affogato selfies. Plaid offal hot chicken gochujang, neutra pour-over sriracha raw denim lumbersexual post-ironic bushwick banh mi pabst.
  Beard kitsch hella venmo try-hard meditation typewriter. Sriracha wayfarers cardigan palo santo, taiyaki street art aesthetic bicycle rights selfies air plant knausgaard blog activated charcoal skateboard. Cardigan 90's literally XOXO sustainable irony offal, forage hoodie copper mug paleo chia roof party la croix. Messenger bag synth mumblecore neutra food truck PBR&B tilde, +1 meditation crucifix YOLO pop-up aesthetic. You probably haven't heard of them gochujang activated charcoal, glossier direct trade ethical pour-over meggings chillwave. Beard hammock YOLO bespoke, cred literally jean shorts taxidermy cliche pabst tote bag sustainable polaroid. Thundercats whatever slow-carb chillwave.
  Taiyaki cold-pressed health goth, art party keffiyeh photo booth iPhone lumbersexual. Keytar listicle cronut 90's snackwave gastropub. Keffiyeh actually kale chips neutra pug tote bag edison bulb flannel umami. Ramps salvia organic, tumblr echo park mixtape biodiesel selvage gastropub bespoke small batch unicorn austin. Salvia locavore disrupt live-edge tumblr helvetica. Next level raclette farm-to-table, af retro lyft distillery sartorial. IPhone raclette actually pabst polaroid, trust fund distillery kale chips sriracha farm-to-table forage bespoke cold-pressed craft beer."
  },
  { title: "Pat Mahomes Saves the Day", user_id: user.id, created_at: DateTime.now, article_text: "I'm baby cray celiac gastropub church-key vaporware messenger bag humblebrag succulents four dollar toast copper mug mixtape. Bitters small batch banh mi, thundercats edison bulb ugh organic. Fingerstache fanny pack authentic unicorn brooklyn, tumeric stumptown occupy PBR&B neutra meditation etsy williamsburg try-hard. Iceland shabby chic ethical gochujang, vape occupy four dollar toast single-origin coffee mlkshk bespoke austin. Keffiyeh semiotics slow-carb beard blog 90's marfa you probably haven't heard of them.
  Coloring book typewriter marfa authentic truffaut cloud bread fixie. Squid brunch vegan blog single-origin coffee, craft beer vice artisan cornhole intelligentsia man braid taxidermy fanny pack selfies. Photo booth pop-up 90's tumblr, kale chips glossier bitters scenester. Taiyaki hell of pabst scenester taxidermy edison bulb etsy, YOLO tumblr marfa retro master cleanse synth hammock. DIY 3 wolf moon pok pok squid, lomo gastropub knausgaard paleo godard pug cloud bread messenger bag banh mi. Cardigan umami austin unicorn artisan messenger bag brooklyn tattooed kale chips godard try-hard heirloom.
  Freegan pitchfork stumptown, retro gochujang kitsch squid chia PBR&B vape wolf. Craft beer hoodie mumblecore pickled woke post-ironic selfies semiotics tumblr. 3 wolf moon fashion axe hammock pok pok shoreditch green juice put a bird on it. Small batch neutra health goth migas vape air plant fixie flannel single-origin coffee tattooed letterpress typewriter pop-up occupy palo santo. Four dollar toast twee pok pok flexitarian organic af four loko photo booth narwhal. DIY butcher affogato palo santo lumbersexual godard lomo, leggings cloud bread.
  Photo booth health goth next level migas letterpress, poke butcher. Shabby chic 8-bit art party banjo, biodiesel you probably haven't heard of them gluten-free ennui aesthetic. Everyday carry lomo franzen pug banjo heirloom. Taiyaki hella lo-fi everyday carry celiac health goth.
  +1 gluten-free kitsch sriracha vinyl palo santo, cronut prism gentrify PBR&B offal vexillologist etsy. Pug church-key poutine street art, blog sartorial blue bottle subway tile neutra franzen YOLO. Banh mi flannel organic chia keffiyeh, tote bag woke meggings everyday carry adaptogen copper mug fingerstache hashtag YOLO. Beard af heirloom plaid, 8-bit tacos yr keffiyeh brooklyn live-edge vape."
  },
  { title: "Coding for Dummies: Give up Now", user_id: user.id, created_at: DateTime.now - 1.day, article_text: "I'm baby selfies tote bag neutra bespoke. Small batch man bun DIY lumbersexual unicorn mustache adaptogen pour-over, irony edison bulb try-hard crucifix. Chicharrones single-origin coffee chambray, occupy messenger bag banh mi affogato pitchfork sriracha kogi pickled tumeric. Lo-fi snackwave mustache, artisan la croix tacos green juice meggings pitchfork banjo. Next level green juice banh mi gochujang portland ethical celiac meggings jean shorts seitan wolf enamel pin raw denim kogi photo booth. Skateboard photo booth single-origin coffee heirloom. Try-hard fixie celiac coloring book.
  Succulents single-origin coffee tofu fashion axe crucifix jean shorts, quinoa everyday carry irony DIY sartorial affogato hammock 8-bit. Neutra keytar health goth umami PBR&B. Narwhal gochujang paleo, master cleanse tote bag chillwave synth PBR&B palo santo. Street art man bun meditation, knausgaard godard occupy hell of lomo jianbing deep v. Pour-over blog adaptogen, af unicorn sartorial distillery food truck XOXO fanny pack hoodie vexillologist listicle quinoa jean shorts.
  Succulents tofu neutra bicycle rights lumbersexual. Chambray edison bulb small batch street art aesthetic fingerstache umami. Drinking vinegar photo booth iceland organic affogato everyday carry. Tacos af kombucha single-origin coffee readymade brooklyn vexillologist activated charcoal tilde adaptogen art party. Glossier literally squid blue bottle, vaporware la croix street art godard DIY ramps pop-up affogato austin cray whatever.
  Intelligentsia squid authentic, flexitarian schlitz yuccie kogi readymade food truck tumeric farm-to-table gluten-free tote bag. Letterpress af scenester affogato YOLO biodiesel everyday carry snackwave. Adaptogen kinfolk lo-fi distillery viral, aesthetic scenester hot chicken cred bespoke lumbersexual subway tile whatever. Butcher slow-carb cred quinoa, before they sold out cronut banh mi dreamcatcher cardigan semiotics chillwave 8-bit distillery kinfolk four loko.
  Single-origin coffee thundercats gochujang fanny pack. Food truck 8-bit tacos fingerstache keffiyeh fam letterpress forage hashtag aesthetic tilde marfa. Franzen listicle prism fam lyft selvage. 90's four dollar toast butcher, everyday carry kickstarter swag church-key VHS la croix celiac. Kinfolk af street art succulents sartorial cronut pickled letterpress."
  },
  { title: "Six ways to boil a Cactus", user_id: user.id, created_at: DateTime.now - 2.day, article_text: "I'm baby whatever raw denim organic, taiyaki godard tumeric knausgaard before they sold out williamsburg tote bag. Stumptown brunch tbh, polaroid pickled cliche dreamcatcher woke squid hoodie. Hot chicken gentrify taxidermy, cronut aesthetic yr heirloom church-key. Fashion axe umami trust fund, ennui artisan DIY 90's. 3 wolf moon tousled meggings single-origin coffee raw denim craft beer VHS deep v wolf. Kickstarter disrupt tofu, asymmetrical paleo messenger bag yr artisan hexagon affogato sustainable. Godard blue bottle stumptown keytar, iPhone irony tofu 90's chicharrones tacos listicle hot chicken sartorial.
  Irony iceland gentrify normcore schlitz. Subway tile shoreditch semiotics normcore sriracha direct trade kitsch cold-pressed. Synth etsy tofu chia, raclette tilde ennui paleo kale chips copper mug. Portland celiac lumbersexual offal prism hot chicken. Fixie microdosing freegan XOXO fanny pack mustache marfa slow-carb salvia ugh pinterest lumbersexual pitchfork.
  Pickled letterpress cardigan deep v 90's fixie salvia yr snackwave live-edge. Celiac banh mi whatever aesthetic, kombucha DIY neutra tbh. Hammock kickstarter shoreditch fanny pack forage farm-to-table freegan hell of letterpress af wolf typewriter art party you probably haven't heard of them. XOXO small batch pork belly, blue bottle plaid copper mug fam gastropub vaporware taxidermy narwhal cliche microdosing prism. Typewriter humblebrag ennui cliche organic. Try-hard squid cold-pressed synth. Chicharrones crucifix trust fund, organic banjo chartreuse you probably haven't heard of them single-origin coffee next level ennui snackwave gochujang.
  Freegan schlitz subway tile snackwave kogi readymade fam man bun distillery ramps fingerstache. Keytar taiyaki franzen leggings locavore. Ethical roof party butcher intelligentsia, pop-up yuccie 90's art party enamel pin put a bird on it whatever DIY. Fingerstache sustainable actually, tilde heirloom waistcoat quinoa meh marfa craft beer neutra church-key hoodie echo park. Crucifix tote bag gluten-free tacos forage hella biodiesel. Gluten-free occupy cronut, lomo scenester woke sartorial paleo jean shorts.
  Activated charcoal aesthetic flannel, fingerstache butcher kitsch deep v leggings roof party poutine jianbing gastropub iceland neutra truffaut. Man braid thundercats umami brunch lumbersexual slow-carb asymmetrical, fingerstache freegan small batch organic. Meh master cleanse fam 3 wolf moon cred. Helvetica ennui organic, cornhole coloring book mumblecore lyft deep v yuccie street art vegan raclette poutine keffiyeh."
  },
  { title: "Teaching Your Dog to Count Cards", user_id: user.id, created_at: DateTime.now - 3.day, article_text: "I'm baby art party pitchfork humblebrag messenger bag, affogato normcore air plant. Deep v meggings you probably haven't heard of them normcore, viral disrupt street art sartorial migas shaman. Umami listicle selvage seitan, lomo butcher gluten-free chicharrones food truck coloring book heirloom migas shaman. Shabby chic helvetica banjo, occupy chartreuse waistcoat pickled cardigan heirloom subway tile vape yuccie salvia wolf yr. Tacos vice XOXO, mlkshk small batch swag put a bird on it polaroid. Fashion axe edison bulb deep v af art party direct trade.
  Next level squid prism etsy readymade 90's, slow-carb fashion axe truffaut vegan banh mi lyft subway tile chartreuse. Bitters chicharrones cliche polaroid schlitz godard migas hell of chambray four loko twee. Brunch plaid next level meditation fashion axe mlkshk. Godard poutine farm-to-table pitchfork. Paleo banh mi wayfarers, gastropub single-origin coffee narwhal tote bag. Jianbing humblebrag lyft vaporware pour-over williamsburg.
  Pinterest blog man bun vinyl. Literally XOXO pug pickled iPhone. Try-hard thundercats dreamcatcher locavore, intelligentsia microdosing vape pabst shabby chic. Viral etsy bespoke, mumblecore actually offal brunch listicle try-hard. 8-bit skateboard normcore literally plaid sustainable. Iceland hella fingerstache, coloring book ennui succulents truffaut chillwave shoreditch gochujang mustache chicharrones snackwave.
  Fanny pack letterpress etsy, everyday carry sriracha cold-pressed kitsch. Microdosing williamsburg pok pok twee, cloud bread tacos vaporware knausgaard poutine. Chambray hexagon kitsch bitters you probably haven't heard of them vinyl affogato succulents yuccie. Polaroid umami retro small batch.
  Twee skateboard green juice banh mi jianbing. Seitan vaporware fixie, authentic yr celiac subway tile raclette synth readymade distillery. Tousled occupy lyft chicharrones, heirloom celiac crucifix woke lumbersexual la croix hexagon street art. Typewriter kogi polaroid waistcoat dreamcatcher."
  }
])
puts "created #{Article.count} Articles"
